server:
  port: 8090

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/testSpringBoot?useUnicode=true&amp&characterEncoding=UTF-8
      username: root
      password: 123456

logging:
  file: ./springboot.log

